name: Update Python Versions
on:
  schedule:
    - cron: '0 7 * * 6'
    # At 07:00 on Saturday
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  update-github-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y curl jq

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: 20

      - name: Check for new python versions
        run: curl "https://endoflife.date/api/python.json" | jq [.[].cycle] > src/versions.json

      - name: Create Pull Request if new versions available
        uses: peter-evans/create-pull-request@v5
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          commit-message: Update Python Versions
          title: Update Python Versions
          branch-suffix: random
