name: Update Python Versions
on:
  schedule:
    - cron: '0 7 * * 6'
    # At 07:00 on Saturday
  workflow_dispatch:

jobs:
  update-python-versions:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y curl jq

      - name: Check for new python versions
        run: ./src/update-versions.sh

      - name: Create Pull Request if new versions available
        uses: peter-evans/create-pull-request@v6
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          commit-message: Update Python Versions
          title: Update Python Versions
          branch-suffix: random
